/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package people;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author František
 */
public class CreateMenu extends javax.swing.JFrame implements KeyListener{
    private Human character;
    private static final DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");
    Date date;
    /**
     * Creates new form CreateMenu
     */
    public CreateMenu() {
        this.setResizable(false);
        this.setUndecorated(true);
        this.setVisible(true);
        setTitle("Create new character");
        initComponents();
        createNewButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classButtonGroup = new javax.swing.ButtonGroup();
        sexButtonGroup = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        classLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        warriorButton = new javax.swing.JRadioButton();
        mageButton = new javax.swing.JRadioButton();
        rangerButton = new javax.swing.JRadioButton();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        createNewButton = new javax.swing.JButton();
        wStrenght = new javax.swing.JLabel();
        mStrenght = new javax.swing.JLabel();
        rStrenght = new javax.swing.JLabel();
        wDexterity = new javax.swing.JLabel();
        mDexterity = new javax.swing.JLabel();
        rDexterity = new javax.swing.JLabel();
        wIntelligence = new javax.swing.JLabel();
        mIntelligence = new javax.swing.JLabel();
        rIntelligence = new javax.swing.JLabel();
        wConstitution = new javax.swing.JLabel();
        mConstitution = new javax.swing.JLabel();
        rConstitution = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        nameLabel.setBackground(new java.awt.Color(102, 102, 102));
        nameLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name:");

        nameTextField.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        classLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classLabel.setText("Class:");

        sexLabel.setBackground(new java.awt.Color(204, 0, 204));
        sexLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        sexLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sexLabel.setText("Sex:");

        classButtonGroup.add(warriorButton);
        warriorButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        warriorButton.setSelected(true);
        warriorButton.setText("Warrior");
        warriorButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                warriorButtonStateChanged(evt);
            }
        });

        classButtonGroup.add(mageButton);
        mageButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        mageButton.setText("Mage");

        classButtonGroup.add(rangerButton);
        rangerButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        rangerButton.setText("Ranger");

        sexButtonGroup.add(maleButton);
        maleButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        maleButton.setSelected(true);
        maleButton.setText("Male");

        sexButtonGroup.add(femaleButton);
        femaleButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        femaleButton.setText("Female");

        createNewButton.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        createNewButton.setText("Create");
        createNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewButtonActionPerformed(evt);
            }
        });

        wStrenght.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wStrenght.setText("Strenght:      13");

        mStrenght.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mStrenght.setText("Strenght:        8");

        rStrenght.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rStrenght.setText("Strenght:      11");

        wDexterity.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wDexterity.setText("Dexterity:        8");

        mDexterity.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mDexterity.setText("Dexterity:      11");

        rDexterity.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rDexterity.setText("Dexterity:     13");

        wIntelligence.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wIntelligence.setText("Intelligence: 11");

        mIntelligence.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mIntelligence.setText("Intelligence: 13");

        rIntelligence.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rIntelligence.setText("Intelligence:  8");

        wConstitution.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        wConstitution.setText("Constitution:  2");

        mConstitution.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mConstitution.setText("Constitution:  0");

        rConstitution.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rConstitution.setText("Constitution:  1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                                .addComponent(createNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(maleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(femaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(259, 259, 259))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wDexterity, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wStrenght, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wIntelligence, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(wConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(mDexterity, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rDexterity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(mStrenght, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(mIntelligence, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(rIntelligence, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rStrenght, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rangerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(classLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleButton)
                    .addComponent(femaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wStrenght, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mStrenght, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(rStrenght, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wDexterity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mDexterity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rDexterity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wIntelligence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mIntelligence, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addComponent(rIntelligence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mConstitution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 164, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new StartMenu().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    private void createNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewButtonActionPerformed


        date = new Date();
        String dateTime = sdf.format(date);
        if (mageButton.isSelected()) {
            character = new Mage("m");
            character.setName(nameTextField.getText());
            character.setToc(dateTime);
            if (maleButton.isSelected()) {
                character.setSex(Human.Sex.MAN);
            } else {
                character.setSex(Human.Sex.WOMAN);
            }
        }
        if (warriorButton.isSelected()) {
            character = new Warrior("w");
            character.setName(nameTextField.getText());
            character.setToc(dateTime);
            if (maleButton.isSelected()) {
                character.setSex(Human.Sex.MAN);
            } else {
                character.setSex(Human.Sex.WOMAN);
            }
        }
        if (rangerButton.isSelected()) {
            character = new Ranger("r");
            character.setName(nameTextField.getText());
            character.setToc(dateTime);
            if (maleButton.isSelected()) {
                character.setSex(Human.Sex.MAN);
            } else {
                character.setSex(Human.Sex.WOMAN);
            }
        }
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("charDataBase.txt", true))) {
            BufferedReader br = new BufferedReader(new FileReader("charDataBase.txt"));
            if (br.readLine() == null) {
                bw.write("toc;name");
                bw.newLine();
            }
            String output = character.getToc() + ";" + character.getName();
            bw.write(output);
            bw.newLine();
            bw.flush();
        } catch (Exception e) {
            System.err.println("There was an error lol you lost your progress get rekt.");
        }
        
        String newChar = dateTime + ".txt";
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(newChar, true))) {
            BufferedReader br = new BufferedReader(new FileReader(newChar));
            if (br.readLine() == null) {
                bw.write("class;name;strength;dexterity;intelligence;constitution;sex;toc;weaponName;weaponDmg;weaponType;"
                        + "chestName;chestArmor;helmetName;helmetArmor;shoesName;shoesArmor;level;attrPoints;exp");
                bw.newLine();
            }
            String output = character.getClass().getSimpleName() + ";"
                    + character.getName() + ";"
                    + character.getStrength() + ";"
                    + character.getDexterity() + ";"
                    + character.getIntelligence() + ";"
                    + character.getConstitution() + ";"
                    + character.getSex() + ";"
                    + character.getToc() + ";"
                    + character.getWeapon().getName() + ";"
                    + character.getWeapon().getDamage() + ";"
                    + character.getWeapon().getType() + ";"
                    + character.getChest().getName() + ";"
                    + character.getChest().getArmor() + ";"
                    + character.getHelmet().getName() + ";"
                    + character.getHelmet().getArmor() + ";"
                    + character.getShoes().getName() + ";"
                    + character.getShoes().getArmor() + ";"
                    + character.getLevel() + ";"
                    + character.getPoint() + ";"
                    + character.getExp() + ";"
                    + character.getHealth() + ";"
                    + character.getX() + ";"
                    + character.getY(); 
            bw.write(output);
            bw.newLine();
            bw.flush();
            new PopupInfoMenu(character).setVisible(true);
        } catch (Exception e) {
            System.err.println("Do souboru se nepovedlo zapsat.");
        }
        
        new WorldMap(character).setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_createNewButtonActionPerformed

    private void warriorButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_warriorButtonStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_warriorButtonStateChanged

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
        if(nameTextField.getText().equalsIgnoreCase("")){
           createNewButton.setEnabled(false);
        }
        else {
            createNewButton.setEnabled(true);
        }
        
    
    }//GEN-LAST:event_nameTextFieldKeyReleased

    public void init() {
        this.addKeyListener((KeyListener) this);
        this.setFocusable(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup classButtonGroup;
    private javax.swing.JLabel classLabel;
    private javax.swing.JButton createNewButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel mConstitution;
    private javax.swing.JLabel mDexterity;
    private javax.swing.JLabel mIntelligence;
    private javax.swing.JLabel mStrenght;
    private javax.swing.JRadioButton mageButton;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel rConstitution;
    private javax.swing.JLabel rDexterity;
    private javax.swing.JLabel rIntelligence;
    private javax.swing.JLabel rStrenght;
    private javax.swing.JRadioButton rangerButton;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel wConstitution;
    private javax.swing.JLabel wDexterity;
    private javax.swing.JLabel wIntelligence;
    private javax.swing.JLabel wStrenght;
    private javax.swing.JRadioButton warriorButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
    
    }

    @Override
    public void keyPressed(KeyEvent ke) {
    
    }

    @Override
    public void keyReleased(KeyEvent ke) {      
    }
}
